version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - ${PUERTOHOST}:${PUERTODOCKER}
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USERDB}
      WORDPRESS_DB_PASSWORD: ${PASSDB}
      WORDPRESS_DB_NAME: ${WPDATABASE}
    volumes:
      - ./wordpress:/var/www/html


  db:
    image: mysql:5.7
    restart: always
    container_name: ${CONTAINERNAMEDB}
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ${WPDATABASE}
      MYSQL_USER: ${USERDB}
      MYSQL_PASSWORD: ${PASSDB}
    ports:
      - ${PUERTOHOSTMYSQL}:${PUERTODOCKERMYSQL}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always         
    links:
      - ${CONTAINERNAMEDB} 
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: ${CONTAINERNAMEDB}
      PMA_PORT: ${PUERTODOCKERMYSQL}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    ports:
      - ${PUERTOHOSTPHPMYADMIN}:${PUERTODOCKERPHPMYADMIN}   